version: 2
jobs:
  build:
    docker:
      - image: regviz/node-xcb
    working_directory: ~/repo
    steps:
      - run: apt-get install -y locales task-japanese
      - run: locale-gen ja_JP.UTF-8
      - run: localedef -f UTF-8 -i ja_JP ja_JP
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run: yarn screenshot
      - run: yarn regression
